//
// Created by chris on 19/02/25.
//

#ifndef SOFTWARE_CONFIGURATION_H
#define SOFTWARE_CONFIGURATION_H

#define WIFI_MGR_EEPROM_START_ADDR 0
#define WIFI_MGR_EEPROM_SIZE 1024
#define USE_LOGGING

#endif //SOFTWARE_CONFIGURATION_H
